module_name: htslib
version: "1.17"
source_url: https://github.com/samtools/htslib/releases/download/1.17/htslib-1.17.tar.bz2
archive_file: htslib-1.17.tar.bz2
target_dir: htslib-1.17
bin_dir: "bin"

