---
- name: copy installer script
  copy:
    src: files/install_R_v4.sh
    dest: "{{ tmpdir }}"
    owner: ubuntu
    group: ubuntu
    mode: '0644'

- name: install-R ver.4
  become: yes
  command: "bash {{ tmpdir }}/install_R_v4.sh"
