---
- name: site
  hosts: localhost
  connection: local
  become: yes
  gather_facts: no
  vars: 
    tmpdir: /home/ubuntu/Ansible/tmp
  roles:
    - conda-pkg-transdecoder-v5.5.0


#=== installed
#    - mod-instl-seqkit-v2.3.1
#    - mod-instl-stringtie
#    - mod-instl-hisat2
#    - mod-instl-htslib
#    - mod-instl-gffread
#    - conda-pkg-braker2
#    - conda-pkg-busco
#   - mod-instl-seqkit
#   - mod-instl-samtools
#   - conda-pkg-salmon
#   - mod-instl-blast
#   - conda-pkg-diamond

#=== not installed
#   - conda-pkg-cutadapt
#   - mod-instl-hisat2
#   - R-instl
