---
- name: prepare_dir_for_module_files
  file:
    path: "/shared/modulefiles/{{ module_name }}"
    state: directory
    owner: "ubuntu"
    group: "ubuntu"
    mode:  "755"

- name: prepare_dir_for_software
  file:
    path: "/shared/software/{{ module_name }}-v{{ version }}"
    state: directory
    owner: "ubuntu"
    group: "ubuntu"
    mode:  "755"

- name: download binaries
  get_url:
    url: https://ftp.ncbi.nlm.nih.gov/pub/datasets/command-line/v2/linux-amd64/datasets
    dest: /shared/software/{{ module_name }}-v{{ version }}/datasets
    mode: '0555'

- name: download binaries
  get_url:
    url: https://ftp.ncbi.nlm.nih.gov/pub/datasets/command-line/v2/linux-amd64/dataformat
    dest: /shared/software/{{ module_name }}-v{{ version }}/dataformat
    mode: '0555'

- name: copy_modulefile_template
  copy: 
    src: files/modulefile.tmpl
    dest: "/shared/modulefiles/{{ module_name }}/{{ version }}"
    owner: ubuntu
    group: ubuntu
    mode: '0755'

- name: add_line_in_modulefile
  ansible.builtin.lineinfile:
    path: "/shared/modulefiles/{{ module_name }}/{{ version }}"
    line: "prepend-path PATH /shared/software/{{ module_name }}-v{{ version }}"

