---
- name: download installer
  get_url: 
    url: "{{ source_url }}"
    dest: "/home/ubuntu/SetUp/work/{{ installer_name }}"
    owner: ubuntu
    
- name: copy-miniconda-installer
  copy:
    src: /home/ubuntu/SetUp/work/{{ installer_name }}
    dest: /home/ubuntu/
    owner: ubuntu
    group: ubuntu
    mode: '0644'
-
  name: install-miniconda
  become: yes
  become_user: ubuntu
  command: bash /home/ubuntu/SetUp/work/{{ installer_name }} -b -p /shared/miniconda

  
