---
- name: prepare_dir_for_module_files
  file:
    path: "/shared/modulefiles/{{ module_name }}"
    state: directory
    owner: "ubuntu"
    group: "ubuntu"
    mode:  "755"

- name: download release archive contining binary from the developer site
  get_url: 
    url: "{{ source_url }}"
    dest: "{{ tmpdir }}/{{ archive_file }}"
    owner: ubuntu

- name: prepare_dir_for_software
  file:
    path: "/shared/software/{{ module_name }}-v{{ version }}"
    state: directory
    owner: "ubuntu"
    group: "ubuntu"
    mode:  "755"

- name: unarchive donwloaded file and copy to target dir
  unarchive:
    src: "{{ tmpdir }}/{{ archive_file }}"
    dest: "/shared/software/{{ module_name }}-v{{ version }}/"
    owner: ubuntu
    group: ubuntu
    mode: '0755'
#    extra_opts: [--strip-components=1]


- name: copy_modulefile_template
  copy: 
    src: files/modulefile.tmpl
    dest: "/shared/modulefiles/{{ module_name }}/{{ version }}"
    owner: ubuntu
    group: ubuntu
    mode: '0755'

- name: create_symbolic_link_to_bin_file_from_short_named_command
  when: bin_alias is defined
  file:
    src:  "./{{ bin_file }}"
    dest: "/shared/software/{{ module_name }}-v{{ version }}/{{ bin_alias }}"
    state: link

- name: add_line_in_modulefile
  ansible.builtin.lineinfile:
    path: "/shared/modulefiles/{{ module_name }}/{{ version }}"
    line: "prepend-path PATH /shared/software/{{ module_name }}-v{{ version }}/"

